apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ethereum-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ethereum
  template:
    metadata:
      labels:
        app: ethereum
    spec:
      containers:
      - name: ethereum-container
        image: schadokar/docker-ethereum:latest
        ports:
        - containerPort: 8545